---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Visualisasi Data dengan `ggplot2`

## Institut Teknologi Statistika dan Bisnis Muhammadiyah Semarang

by Deden Istiawan

<!-- badges: start -->
<!-- badges: end -->


### Outline 

-  Conceptual hierarchy of data viz
- `ggplot2` basics review
    - Aesthetic mapping
    - Themes
    - Labels
    - Facets (& facet grids vs facet wraps)
    - Getting things in order (e.g. fct_reorder)
- Advanced customization in `ggplot2`
    - `scales` for thoughtful breaks and labels
    - ...and color schemes (+ `paletteer`!)
    - In the weeds of themes (gridlines, panel colors, margins, etc.)
    - Direct annotation (as an alternative to legends)
    - Repulsive labels (e.g. `ggrepel`)
    - Highlighting for clarity (e.g. with `gghighlight`)
- Compound figures with `patchwork`
- A few new graph types to consider
    - Marginal plot
    - Beeswarm plots with `ggbeeswarm`
    - Heatmaps with `geom_tile()`
    - A map! in `ggplot2`
- Export & save your graphs
- Keep learning


#### General use packages:

- `tidyverse`
- `here`
- `janitor`

#### Specifically for plots:

- `patchwork`
- `ggrepel`
- `gghighlight`
- `paletteer`
- `ggExtra`
- `ggbeeswarm`

#### Spatial data simplified:

- `sf`

#### And for another dataset we'll explore:

- `gapminder`
